/**
 * Country calling codes, with the country's name in each of the app's languages.
 *
 * Generated once and committed rather than derived at runtime from
 * `Intl.DisplayNames`: the select is rendered on the server and hydrated in the
 * browser, and the two ICU builds do not have to agree on every country's name.
 * A static table cannot disagree with itself.
 *
 * Codes are E.164 calling codes without the `+`, matching what
 * `src/features/whatsapp/phone.ts` works in. Several countries legitimately
 * share one — `+1` across North America, `+44` across the British Isles — which
 * is why `splitPhone` in `./phone-format.ts` resolves a number to a calling code
 * and not to a country.
 *
 * Regenerating: this is data, not logic. Keep the helpers in `./phone-format.ts`
 * so re-running the generator cannot overwrite them.
 */

export type CountryCode = keyof typeof COUNTRIES;

export const COUNTRIES = {
  AF: { dial: '93', ar: 'أفغانستان', en: 'Afghanistan' },
  AL: { dial: '355', ar: 'ألبانيا', en: 'Albania' },
  DZ: { dial: '213', ar: 'الجزائر', en: 'Algeria' },
  AS: { dial: '1684', ar: 'ساموا الأمريكية', en: 'American Samoa' },
  AD: { dial: '376', ar: 'أندورا', en: 'Andorra' },
  AO: { dial: '244', ar: 'أنغولا', en: 'Angola' },
  AI: { dial: '1264', ar: 'أنغويلا', en: 'Anguilla' },
  AG: { dial: '1268', ar: 'أنتيغوا وبربودا', en: 'Antigua & Barbuda' },
  AR: { dial: '54', ar: 'الأرجنتين', en: 'Argentina' },
  AM: { dial: '374', ar: 'أرمينيا', en: 'Armenia' },
  AW: { dial: '297', ar: 'أروبا', en: 'Aruba' },
  AU: { dial: '61', ar: 'أستراليا', en: 'Australia' },
  AT: { dial: '43', ar: 'النمسا', en: 'Austria' },
  AZ: { dial: '994', ar: 'أذربيجان', en: 'Azerbaijan' },
  BS: { dial: '1242', ar: 'جزر البهاما', en: 'Bahamas' },
  BH: { dial: '973', ar: 'البحرين', en: 'Bahrain' },
  BD: { dial: '880', ar: 'بنغلاديش', en: 'Bangladesh' },
  BB: { dial: '1246', ar: 'بربادوس', en: 'Barbados' },
  BY: { dial: '375', ar: 'بيلاروس', en: 'Belarus' },
  BE: { dial: '32', ar: 'بلجيكا', en: 'Belgium' },
  BZ: { dial: '501', ar: 'بليز', en: 'Belize' },
  BJ: { dial: '229', ar: 'بنين', en: 'Benin' },
  BM: { dial: '1441', ar: 'برمودا', en: 'Bermuda' },
  BT: { dial: '975', ar: 'بوتان', en: 'Bhutan' },
  BO: { dial: '591', ar: 'بوليفيا', en: 'Bolivia' },
  BQ: { dial: '599', ar: 'هولندا الكاريبية', en: 'Caribbean Netherlands' },
  BA: { dial: '387', ar: 'البوسنة والهرسك', en: 'Bosnia & Herzegovina' },
  BW: { dial: '267', ar: 'بوتسوانا', en: 'Botswana' },
  BR: { dial: '55', ar: 'البرازيل', en: 'Brazil' },
  IO: { dial: '246', ar: 'الإقليم البريطاني في المحيط الهندي', en: 'British Indian Ocean Territory' },
  BN: { dial: '673', ar: 'بروناي', en: 'Brunei' },
  BG: { dial: '359', ar: 'بلغاريا', en: 'Bulgaria' },
  BF: { dial: '226', ar: 'بوركينا فاسو', en: 'Burkina Faso' },
  BI: { dial: '257', ar: 'بوروندي', en: 'Burundi' },
  CV: { dial: '238', ar: 'الرأس الأخضر', en: 'Cape Verde' },
  KH: { dial: '855', ar: 'كمبوديا', en: 'Cambodia' },
  CM: { dial: '237', ar: 'الكاميرون', en: 'Cameroon' },
  CA: { dial: '1', ar: 'كندا', en: 'Canada' },
  KY: { dial: '1345', ar: 'جزر كايمان', en: 'Cayman Islands' },
  CF: { dial: '236', ar: 'جمهورية أفريقيا الوسطى', en: 'Central African Republic' },
  TD: { dial: '235', ar: 'تشاد', en: 'Chad' },
  CL: { dial: '56', ar: 'تشيلي', en: 'Chile' },
  CN: { dial: '86', ar: 'الصين', en: 'China' },
  CO: { dial: '57', ar: 'كولومبيا', en: 'Colombia' },
  KM: { dial: '269', ar: 'جزر القمر', en: 'Comoros' },
  CG: { dial: '242', ar: 'الكونغو - برازافيل', en: 'Congo - Brazzaville' },
  CD: { dial: '243', ar: 'الكونغو - كينشاسا', en: 'Congo - Kinshasa' },
  CK: { dial: '682', ar: 'جزر كوك', en: 'Cook Islands' },
  CR: { dial: '506', ar: 'كوستاريكا', en: 'Costa Rica' },
  CI: { dial: '225', ar: 'ساحل العاج', en: 'Côte d’Ivoire' },
  HR: { dial: '385', ar: 'كرواتيا', en: 'Croatia' },
  CU: { dial: '53', ar: 'كوبا', en: 'Cuba' },
  CW: { dial: '599', ar: 'كوراساو', en: 'Curaçao' },
  CY: { dial: '357', ar: 'قبرص', en: 'Cyprus' },
  CZ: { dial: '420', ar: 'التشيك', en: 'Czechia' },
  DK: { dial: '45', ar: 'الدانمرك', en: 'Denmark' },
  DJ: { dial: '253', ar: 'جيبوتي', en: 'Djibouti' },
  DM: { dial: '1767', ar: 'دومينيكا', en: 'Dominica' },
  DO: { dial: '1809', ar: 'جمهورية الدومينيكان', en: 'Dominican Republic' },
  EC: { dial: '593', ar: 'الإكوادور', en: 'Ecuador' },
  EG: { dial: '20', ar: 'مصر', en: 'Egypt' },
  SV: { dial: '503', ar: 'السلفادور', en: 'El Salvador' },
  GQ: { dial: '240', ar: 'غينيا الاستوائية', en: 'Equatorial Guinea' },
  ER: { dial: '291', ar: 'إريتريا', en: 'Eritrea' },
  EE: { dial: '372', ar: 'إستونيا', en: 'Estonia' },
  SZ: { dial: '268', ar: 'إسواتيني', en: 'Eswatini' },
  ET: { dial: '251', ar: 'إثيوبيا', en: 'Ethiopia' },
  FK: { dial: '500', ar: 'جزر فوكلاند', en: 'Falkland Islands' },
  FO: { dial: '298', ar: 'جزر فارو', en: 'Faroe Islands' },
  FJ: { dial: '679', ar: 'فيجي', en: 'Fiji' },
  FI: { dial: '358', ar: 'فنلندا', en: 'Finland' },
  FR: { dial: '33', ar: 'فرنسا', en: 'France' },
  GF: { dial: '594', ar: 'غويانا الفرنسية', en: 'French Guiana' },
  PF: { dial: '689', ar: 'بولينيزيا الفرنسية', en: 'French Polynesia' },
  GA: { dial: '241', ar: 'الغابون', en: 'Gabon' },
  GM: { dial: '220', ar: 'غامبيا', en: 'Gambia' },
  GE: { dial: '995', ar: 'جورجيا', en: 'Georgia' },
  DE: { dial: '49', ar: 'ألمانيا', en: 'Germany' },
  GH: { dial: '233', ar: 'غانا', en: 'Ghana' },
  GI: { dial: '350', ar: 'جبل طارق', en: 'Gibraltar' },
  GR: { dial: '30', ar: 'اليونان', en: 'Greece' },
  GL: { dial: '299', ar: 'غرينلاند', en: 'Greenland' },
  GD: { dial: '1473', ar: 'غرينادا', en: 'Grenada' },
  GP: { dial: '590', ar: 'غوادلوب', en: 'Guadeloupe' },
  GU: { dial: '1671', ar: 'غوام', en: 'Guam' },
  GT: { dial: '502', ar: 'غواتيمالا', en: 'Guatemala' },
  GG: { dial: '44', ar: 'غيرنزي', en: 'Guernsey' },
  GN: { dial: '224', ar: 'غينيا', en: 'Guinea' },
  GW: { dial: '245', ar: 'غينيا بيساو', en: 'Guinea-Bissau' },
  GY: { dial: '592', ar: 'غيانا', en: 'Guyana' },
  HT: { dial: '509', ar: 'هايتي', en: 'Haiti' },
  HN: { dial: '504', ar: 'هندوراس', en: 'Honduras' },
  HK: { dial: '852', ar: 'هونغ كونغ الصينية (منطقة إدارية خاصة)', en: 'Hong Kong SAR China' },
  HU: { dial: '36', ar: 'هنغاريا', en: 'Hungary' },
  IS: { dial: '354', ar: 'آيسلندا', en: 'Iceland' },
  IN: { dial: '91', ar: 'الهند', en: 'India' },
  ID: { dial: '62', ar: 'إندونيسيا', en: 'Indonesia' },
  IR: { dial: '98', ar: 'إيران', en: 'Iran' },
  IQ: { dial: '964', ar: 'العراق', en: 'Iraq' },
  IE: { dial: '353', ar: 'أيرلندا', en: 'Ireland' },
  IM: { dial: '44', ar: 'جزيرة مان', en: 'Isle of Man' },
  IL: { dial: '972', ar: 'إسرائيل', en: 'Israel' },
  IT: { dial: '39', ar: 'إيطاليا', en: 'Italy' },
  JM: { dial: '1876', ar: 'جامايكا', en: 'Jamaica' },
  JP: { dial: '81', ar: 'اليابان', en: 'Japan' },
  JE: { dial: '44', ar: 'جيرسي', en: 'Jersey' },
  JO: { dial: '962', ar: 'الأردن', en: 'Jordan' },
  KZ: { dial: '7', ar: 'كازاخستان', en: 'Kazakhstan' },
  KE: { dial: '254', ar: 'كينيا', en: 'Kenya' },
  KI: { dial: '686', ar: 'كيريباتي', en: 'Kiribati' },
  KP: { dial: '850', ar: 'كوريا الشمالية', en: 'North Korea' },
  KR: { dial: '82', ar: 'كوريا الجنوبية', en: 'South Korea' },
  KW: { dial: '965', ar: 'الكويت', en: 'Kuwait' },
  KG: { dial: '996', ar: 'قيرغيزستان', en: 'Kyrgyzstan' },
  LA: { dial: '856', ar: 'لاوس', en: 'Laos' },
  LV: { dial: '371', ar: 'لاتفيا', en: 'Latvia' },
  LB: { dial: '961', ar: 'لبنان', en: 'Lebanon' },
  LS: { dial: '266', ar: 'ليسوتو', en: 'Lesotho' },
  LR: { dial: '231', ar: 'ليبيريا', en: 'Liberia' },
  LY: { dial: '218', ar: 'ليبيا', en: 'Libya' },
  LI: { dial: '423', ar: 'ليختنشتاين', en: 'Liechtenstein' },
  LT: { dial: '370', ar: 'ليتوانيا', en: 'Lithuania' },
  LU: { dial: '352', ar: 'لوكسمبورغ', en: 'Luxembourg' },
  MO: { dial: '853', ar: 'منطقة ماكاو الإدارية الخاصة', en: 'Macao SAR China' },
  MG: { dial: '261', ar: 'مدغشقر', en: 'Madagascar' },
  MW: { dial: '265', ar: 'ملاوي', en: 'Malawi' },
  MY: { dial: '60', ar: 'ماليزيا', en: 'Malaysia' },
  MV: { dial: '960', ar: 'جزر المالديف', en: 'Maldives' },
  ML: { dial: '223', ar: 'مالي', en: 'Mali' },
  MT: { dial: '356', ar: 'مالطا', en: 'Malta' },
  MH: { dial: '692', ar: 'جزر مارشال', en: 'Marshall Islands' },
  MQ: { dial: '596', ar: 'جزر المارتينيك', en: 'Martinique' },
  MR: { dial: '222', ar: 'موريتانيا', en: 'Mauritania' },
  MU: { dial: '230', ar: 'موريشيوس', en: 'Mauritius' },
  YT: { dial: '262', ar: 'مايوت', en: 'Mayotte' },
  MX: { dial: '52', ar: 'المكسيك', en: 'Mexico' },
  FM: { dial: '691', ar: 'ميكرونيزيا', en: 'Micronesia' },
  MD: { dial: '373', ar: 'مولدوفا', en: 'Moldova' },
  MC: { dial: '377', ar: 'موناكو', en: 'Monaco' },
  MN: { dial: '976', ar: 'منغوليا', en: 'Mongolia' },
  ME: { dial: '382', ar: 'الجبل الأسود', en: 'Montenegro' },
  MS: { dial: '1664', ar: 'مونتسرات', en: 'Montserrat' },
  MA: { dial: '212', ar: 'المغرب', en: 'Morocco' },
  MZ: { dial: '258', ar: 'موزمبيق', en: 'Mozambique' },
  MM: { dial: '95', ar: 'ميانمار (بورما)', en: 'Myanmar (Burma)' },
  NA: { dial: '264', ar: 'ناميبيا', en: 'Namibia' },
  NR: { dial: '674', ar: 'ناورو', en: 'Nauru' },
  NP: { dial: '977', ar: 'نيبال', en: 'Nepal' },
  NL: { dial: '31', ar: 'هولندا', en: 'Netherlands' },
  NC: { dial: '687', ar: 'كاليدونيا الجديدة', en: 'New Caledonia' },
  NZ: { dial: '64', ar: 'نيوزيلندا', en: 'New Zealand' },
  NI: { dial: '505', ar: 'نيكاراغوا', en: 'Nicaragua' },
  NE: { dial: '227', ar: 'النيجر', en: 'Niger' },
  NG: { dial: '234', ar: 'نيجيريا', en: 'Nigeria' },
  NU: { dial: '683', ar: 'نيوي', en: 'Niue' },
  NF: { dial: '672', ar: 'جزيرة نورفولك', en: 'Norfolk Island' },
  MK: { dial: '389', ar: 'مقدونيا الشمالية', en: 'North Macedonia' },
  MP: { dial: '1670', ar: 'جزر ماريانا الشمالية', en: 'Northern Mariana Islands' },
  NO: { dial: '47', ar: 'النرويج', en: 'Norway' },
  OM: { dial: '968', ar: 'عُمان', en: 'Oman' },
  PK: { dial: '92', ar: 'باكستان', en: 'Pakistan' },
  PW: { dial: '680', ar: 'بالاو', en: 'Palau' },
  PS: { dial: '970', ar: 'الأراضي الفلسطينية', en: 'Palestinian Territories' },
  PA: { dial: '507', ar: 'بنما', en: 'Panama' },
  PG: { dial: '675', ar: 'بابوا غينيا الجديدة', en: 'Papua New Guinea' },
  PY: { dial: '595', ar: 'باراغواي', en: 'Paraguay' },
  PE: { dial: '51', ar: 'بيرو', en: 'Peru' },
  PH: { dial: '63', ar: 'الفلبين', en: 'Philippines' },
  PL: { dial: '48', ar: 'بولندا', en: 'Poland' },
  PT: { dial: '351', ar: 'البرتغال', en: 'Portugal' },
  PR: { dial: '1787', ar: 'بورتوريكو', en: 'Puerto Rico' },
  QA: { dial: '974', ar: 'قطر', en: 'Qatar' },
  RE: { dial: '262', ar: 'روينيون', en: 'Réunion' },
  RO: { dial: '40', ar: 'رومانيا', en: 'Romania' },
  RU: { dial: '7', ar: 'روسيا', en: 'Russia' },
  RW: { dial: '250', ar: 'رواندا', en: 'Rwanda' },
  BL: { dial: '590', ar: 'سان بارتليمي', en: 'St. Barthélemy' },
  SH: { dial: '290', ar: 'سانت هيلينا', en: 'St. Helena' },
  KN: { dial: '1869', ar: 'سانت كيتس ونيفيس', en: 'St. Kitts & Nevis' },
  LC: { dial: '1758', ar: 'سانت لوسيا', en: 'St. Lucia' },
  MF: { dial: '590', ar: 'سان مارتن', en: 'St. Martin' },
  PM: { dial: '508', ar: 'سان بيير ومكويلون', en: 'St. Pierre & Miquelon' },
  VC: { dial: '1784', ar: 'سانت فنسنت وجزر غرينادين', en: 'St. Vincent & Grenadines' },
  WS: { dial: '685', ar: 'ساموا', en: 'Samoa' },
  SM: { dial: '378', ar: 'سان مارينو', en: 'San Marino' },
  ST: { dial: '239', ar: 'ساو تومي وبرينسيبي', en: 'São Tomé & Príncipe' },
  SA: { dial: '966', ar: 'المملكة العربية السعودية', en: 'Saudi Arabia' },
  SN: { dial: '221', ar: 'السنغال', en: 'Senegal' },
  RS: { dial: '381', ar: 'صربيا', en: 'Serbia' },
  SC: { dial: '248', ar: 'سيشل', en: 'Seychelles' },
  SL: { dial: '232', ar: 'سيراليون', en: 'Sierra Leone' },
  SG: { dial: '65', ar: 'سنغافورة', en: 'Singapore' },
  SX: { dial: '1721', ar: 'سانت مارتن', en: 'Sint Maarten' },
  SK: { dial: '421', ar: 'سلوفاكيا', en: 'Slovakia' },
  SI: { dial: '386', ar: 'سلوفينيا', en: 'Slovenia' },
  SB: { dial: '677', ar: 'جزر سليمان', en: 'Solomon Islands' },
  SO: { dial: '252', ar: 'الصومال', en: 'Somalia' },
  ZA: { dial: '27', ar: 'جنوب أفريقيا', en: 'South Africa' },
  SS: { dial: '211', ar: 'جنوب السودان', en: 'South Sudan' },
  ES: { dial: '34', ar: 'إسبانيا', en: 'Spain' },
  LK: { dial: '94', ar: 'سريلانكا', en: 'Sri Lanka' },
  SD: { dial: '249', ar: 'السودان', en: 'Sudan' },
  SR: { dial: '597', ar: 'سورينام', en: 'Suriname' },
  SJ: { dial: '47', ar: 'سفالبارد وجان ماين', en: 'Svalbard & Jan Mayen' },
  SE: { dial: '46', ar: 'السويد', en: 'Sweden' },
  CH: { dial: '41', ar: 'سويسرا', en: 'Switzerland' },
  SY: { dial: '963', ar: 'سوريا', en: 'Syria' },
  TW: { dial: '886', ar: 'تايوان', en: 'Taiwan' },
  TJ: { dial: '992', ar: 'طاجيكستان', en: 'Tajikistan' },
  TZ: { dial: '255', ar: 'تنزانيا', en: 'Tanzania' },
  TH: { dial: '66', ar: 'تايلاند', en: 'Thailand' },
  TL: { dial: '670', ar: 'تيمور - ليشتي', en: 'Timor-Leste' },
  TG: { dial: '228', ar: 'توغو', en: 'Togo' },
  TK: { dial: '690', ar: 'توكيلاو', en: 'Tokelau' },
  TO: { dial: '676', ar: 'تونغا', en: 'Tonga' },
  TT: { dial: '1868', ar: 'ترينيداد وتوباغو', en: 'Trinidad & Tobago' },
  TN: { dial: '216', ar: 'تونس', en: 'Tunisia' },
  TR: { dial: '90', ar: 'تركيا', en: 'Türkiye' },
  TM: { dial: '993', ar: 'تركمانستان', en: 'Turkmenistan' },
  TC: { dial: '1649', ar: 'جزر توركس وكايكوس', en: 'Turks & Caicos Islands' },
  TV: { dial: '688', ar: 'توفالو', en: 'Tuvalu' },
  UG: { dial: '256', ar: 'أوغندا', en: 'Uganda' },
  UA: { dial: '380', ar: 'أوكرانيا', en: 'Ukraine' },
  AE: { dial: '971', ar: 'الإمارات العربية المتحدة', en: 'United Arab Emirates' },
  GB: { dial: '44', ar: 'المملكة المتحدة', en: 'United Kingdom' },
  US: { dial: '1', ar: 'الولايات المتحدة', en: 'United States' },
  UY: { dial: '598', ar: 'أورغواي', en: 'Uruguay' },
  UZ: { dial: '998', ar: 'أوزبكستان', en: 'Uzbekistan' },
  VU: { dial: '678', ar: 'فانواتو', en: 'Vanuatu' },
  VA: { dial: '39', ar: 'الفاتيكان', en: 'Vatican City' },
  VE: { dial: '58', ar: 'فنزويلا', en: 'Venezuela' },
  VN: { dial: '84', ar: 'فيتنام', en: 'Vietnam' },
  VG: { dial: '1284', ar: 'جزر فيرجن البريطانية', en: 'British Virgin Islands' },
  VI: { dial: '1340', ar: 'جزر فيرجن الأمريكية', en: 'U.S. Virgin Islands' },
  WF: { dial: '681', ar: 'جزر والس وفوتونا', en: 'Wallis & Futuna' },
  EH: { dial: '212', ar: 'الصحراء الغربية', en: 'Western Sahara' },
  YE: { dial: '967', ar: 'اليمن', en: 'Yemen' },
  ZM: { dial: '260', ar: 'زامبيا', en: 'Zambia' },
  ZW: { dial: '263', ar: 'زيمبابوي', en: 'Zimbabwe' },
  AX: { dial: '358', ar: 'جزر آلاند', en: 'Åland Islands' },
} as const satisfies Record<string, { dial: string; ar: string; en: string }>;

/**
 * The clinic's own country, offered first and selected for a new client.
 *
 * The same default `src/features/whatsapp/config.ts` falls back to, so a number
 * typed here and a number normalised for WhatsApp agree about what `0599…` means.
 */
export const DEFAULT_COUNTRY: CountryCode = 'PS';

/**
 * Display order per language, precomputed for the same reason the names are:
 * collation is another thing two ICU builds need not agree on, and a select
 * whose options are ordered differently on the server and the client is a
 * hydration mismatch.
 */
export const COUNTRY_ORDER: Record<'ar' | 'en', readonly CountryCode[]> = {
  ar: [
  'IS', 'ET', 'AZ', 'AM', 'AW', 'ER', 'ES', 'AU', 'EE', 'IL', 'SZ', 'AF', 'PS', 'AR', 'JO', 'IO', 'EC', 'AE',
  'AL', 'BH', 'BR', 'PT', 'BA', 'CZ', 'ME', 'DZ', 'DK', 'CV', 'SV', 'SN', 'SD', 'SE', 'EH', 'SO', 'CN', 'IQ',
  'GA', 'VA', 'PH', 'CM', 'CG', 'CD', 'KW', 'DE', 'MA', 'MX', 'SA', 'GB', 'NO', 'AT', 'NE', 'IN', 'US', 'JP',
  'YE', 'GR', 'AG', 'AD', 'ID', 'AO', 'AI', 'UY', 'UZ', 'UG', 'UA', 'IR', 'IE', 'IT', 'PG', 'PY', 'PK', 'PW',
  'BB', 'BM', 'BN', 'BE', 'BG', 'BZ', 'BD', 'PA', 'BJ', 'BT', 'BW', 'PR', 'BF', 'BI', 'PL', 'BO', 'PF', 'PE',
  'BY', 'TH', 'TW', 'TM', 'TR', 'TT', 'TD', 'CL', 'TZ', 'TG', 'TV', 'TK', 'TN', 'TO', 'TL', 'JM', 'GI', 'AX',
  'BS', 'KM', 'MQ', 'MV', 'TC', 'SB', 'FO', 'FK', 'VI', 'VG', 'KY', 'CK', 'MH', 'MP', 'WF', 'IM', 'NF', 'CF',
  'DO', 'ZA', 'SS', 'GE', 'DJ', 'JE', 'DM', 'RW', 'RU', 'RO', 'RE', 'ZM', 'ZW', 'CI', 'WS', 'AS', 'BL', 'PM',
  'MF', 'SM', 'VC', 'KN', 'LC', 'SX', 'SH', 'ST', 'LK', 'SJ', 'SK', 'SI', 'SG', 'SY', 'SR', 'CH', 'SL', 'SC',
  'RS', 'TJ', 'OM', 'GM', 'GH', 'GD', 'GL', 'GT', 'GP', 'GU', 'GF', 'GY', 'GG', 'GN', 'GQ', 'GW', 'VU', 'FR',
  'VE', 'FI', 'VN', 'FJ', 'CY', 'QA', 'KG', 'KZ', 'NC', 'HR', 'KH', 'CA', 'CU', 'CW', 'KR', 'KP', 'CR', 'CO',
  'KI', 'KE', 'LV', 'LA', 'LB', 'LU', 'LY', 'LR', 'LT', 'LI', 'LS', 'MT', 'ML', 'MY', 'YT', 'MG', 'EG', 'MK',
  'MW', 'MO', 'MN', 'MR', 'MU', 'MZ', 'MD', 'MC', 'MS', 'MM', 'FM', 'NA', 'NR', 'NP', 'NG', 'NI', 'NZ', 'NU',
  'HT', 'HN', 'HU', 'NL', 'BQ', 'HK',
  ],
  en: [
  'AF', 'AX', 'AL', 'DZ', 'AS', 'AD', 'AO', 'AI', 'AG', 'AR', 'AM', 'AW', 'AU', 'AT', 'AZ', 'BS', 'BH', 'BD',
  'BB', 'BY', 'BE', 'BZ', 'BJ', 'BM', 'BT', 'BO', 'BA', 'BW', 'BR', 'IO', 'VG', 'BN', 'BG', 'BF', 'BI', 'KH',
  'CM', 'CA', 'CV', 'BQ', 'KY', 'CF', 'TD', 'CL', 'CN', 'CO', 'KM', 'CG', 'CD', 'CK', 'CR', 'CI', 'HR', 'CU',
  'CW', 'CY', 'CZ', 'DK', 'DJ', 'DM', 'DO', 'EC', 'EG', 'SV', 'GQ', 'ER', 'EE', 'SZ', 'ET', 'FK', 'FO', 'FJ',
  'FI', 'FR', 'GF', 'PF', 'GA', 'GM', 'GE', 'DE', 'GH', 'GI', 'GR', 'GL', 'GD', 'GP', 'GU', 'GT', 'GG', 'GN',
  'GW', 'GY', 'HT', 'HN', 'HK', 'HU', 'IS', 'IN', 'ID', 'IR', 'IQ', 'IE', 'IM', 'IL', 'IT', 'JM', 'JP', 'JE',
  'JO', 'KZ', 'KE', 'KI', 'KW', 'KG', 'LA', 'LV', 'LB', 'LS', 'LR', 'LY', 'LI', 'LT', 'LU', 'MO', 'MG', 'MW',
  'MY', 'MV', 'ML', 'MT', 'MH', 'MQ', 'MR', 'MU', 'YT', 'MX', 'FM', 'MD', 'MC', 'MN', 'ME', 'MS', 'MA', 'MZ',
  'MM', 'NA', 'NR', 'NP', 'NL', 'NC', 'NZ', 'NI', 'NE', 'NG', 'NU', 'NF', 'KP', 'MK', 'MP', 'NO', 'OM', 'PK',
  'PW', 'PS', 'PA', 'PG', 'PY', 'PE', 'PH', 'PL', 'PT', 'PR', 'QA', 'RE', 'RO', 'RU', 'RW', 'WS', 'SM', 'ST',
  'SA', 'SN', 'RS', 'SC', 'SL', 'SG', 'SX', 'SK', 'SI', 'SB', 'SO', 'ZA', 'KR', 'SS', 'ES', 'LK', 'BL', 'SH',
  'KN', 'LC', 'MF', 'PM', 'VC', 'SD', 'SR', 'SJ', 'SE', 'CH', 'SY', 'TW', 'TJ', 'TZ', 'TH', 'TL', 'TG', 'TK',
  'TO', 'TT', 'TN', 'TR', 'TM', 'TC', 'TV', 'VI', 'UG', 'UA', 'AE', 'GB', 'US', 'UY', 'UZ', 'VU', 'VA', 'VE',
  'VN', 'WF', 'EH', 'YE', 'ZM', 'ZW',
  ],
};
