/**
 * Runs a plan review from the command line.
 *
 *   bun run plan:review                          # newest plan in this database
 *   bun run plan:review --plan <uuid>
 *   bun run plan:review --file plan.txt          # a week from another database
 *   bun run plan:review --model gpt-4o-mini      # compare two models on one plan
 *   bun run plan:review --print-only             # exactly what the model is shown
 *   bun run plan:review --out review.json
 *
 * The review itself lives in `src/features/weekly-plans/review.ts`, where the
 * app's own button reaches it. This is the same call with a terminal around it:
 * useful for trying a prompt or a model against weeks that already exist, and for
 * reviewing a plan exported from production, which this machine's database does
 * not hold.
 *
 * `--file` takes a plan already rendered to text. Nothing is checked
 * arithmetically in that mode, because there is no board to check, and the model
 * is told so rather than left to assume the numbers were vetted.
 */
import { desc, eq } from 'drizzle-orm';

import { db } from '@/db';
import { weeklyPlans } from '@/db/schema';
import { getLlmTransport } from '@/features/weekly-plans/llm';
import { getBoard } from '@/features/weekly-plans/queries';
import {
  arithmeticFindings,
  renderPlanForReview,
  reviewPayloadFor,
  type PlanReview,
} from '@/features/weekly-plans/review';

/** What a million tokens costs, for the line at the bottom of the report. */
const PRICES: Record<string, { input: number; output: number }> = {
  'gpt-4o-mini': { input: 0.15, output: 0.6 },
  'gpt-4o': { input: 2.5, output: 10 },
  'gpt-5.6-luna': { input: 0.2, output: 1.2 },
  'gpt-5.6-terra': { input: 2, output: 12 },
  'gpt-5.6-sol': { input: 4, output: 20 },
};

const DAY_NAMES_AR = ['الأحد', 'الاثنين', 'الثلاثاء', 'الأربعاء', 'الخميس', 'الجمعة', 'السبت'];
const SEVERITY_RANK: Record<string, number> = { high: 0, medium: 1, low: 2 };

function arg(name: string): string | null {
  const index = process.argv.indexOf(`--${name}`);
  return index === -1 ? null : (process.argv[index + 1] ?? null);
}

/** A plan text and the checks that ran over it, from whichever source was named. */
async function loadPlan(): Promise<{ text: string; checks: string[] | null; label: string }> {
  const file = arg('file');

  if (file) {
    return { text: await Bun.file(file).text(), checks: null, label: file };
  }

  const planId = arg('plan');

  const [row] = planId
    ? await db
        .select({ id: weeklyPlans.id, clinicId: weeklyPlans.clinicId })
        .from(weeklyPlans)
        .where(eq(weeklyPlans.id, planId))
        .limit(1)
    : await db
        .select({ id: weeklyPlans.id, clinicId: weeklyPlans.clinicId })
        .from(weeklyPlans)
        .orderBy(desc(weeklyPlans.createdAt))
        .limit(1);

  if (!row) {
    console.error(planId ? `No plan ${planId} in this database.` : 'This database holds no plans.');
    process.exit(1);
  }

  const board = await getBoard(row.clinicId, row.id);

  if (!board) {
    console.error(`Plan ${row.id} could not be loaded.`);
    process.exit(1);
  }

  console.log(`Plan ${board.id} · week of ${board.weekStartDate} · ${board.status}`);
  console.log(`Generated by ${board.generatedBy}${board.model ? ` (${board.model})` : ''}`);

  return {
    text: renderPlanForReview(board),
    checks: arithmeticFindings(board),
    label: board.id,
  };
}

function printReport(review: PlanReview, model: string, durationMs: number, usage: {
  promptTokens: number | null;
  completionTokens: number | null;
}): void {
  console.log('');
  console.log(`الحكم: ${review.verdict}`);
  console.log(review.summaryAr);
  console.log('');
  console.log(`الملاحظات (${review.findings.length}):`);

  const sorted = [...review.findings].sort(
    (a, b) => (SEVERITY_RANK[a.severity] ?? 3) - (SEVERITY_RANK[b.severity] ?? 3),
  );

  for (const finding of sorted) {
    const where =
      finding.dayOfWeek === null
        ? 'الأسبوع'
        : `${DAY_NAMES_AR[finding.dayOfWeek] ?? ''} · ${finding.slotKey}`;

    console.log('');
    console.log(`  [${finding.severity}] [${finding.category}] ${where}`);
    console.log(`    المشكلة: ${finding.problemAr}`);
    console.log(`    الاقتراح: ${finding.suggestionAr}`);
  }

  const price = PRICES[model] ?? PRICES[model.replace(/-\d{4}-\d{2}-\d{2}$/, '')];
  const cost =
    price && usage.promptTokens !== null && usage.completionTokens !== null
      ? (usage.promptTokens * price.input + usage.completionTokens * price.output) / 1_000_000
      : null;

  console.log('');
  console.log(
    [
      `النموذج ${model}`,
      `${(durationMs / 1000).toFixed(1)}s`,
      `دخل ${usage.promptTokens ?? '?'}`,
      `خرج ${usage.completionTokens ?? '?'}`,
      cost === null ? 'التكلفة غير معروفة' : `التكلفة ≈ $${cost.toFixed(4)}`,
    ].join(' · '),
  );
}

async function main(): Promise<void> {
  const { text, checks, label } = await loadPlan();

  if (checks === null) {
    console.log(`Reviewing ${label} — no arithmetic checks, this copy has no board behind it.`);
  } else {
    console.log('');
    console.log(`Arithmetic checks found ${checks.length} problem(s):`);
    for (const line of checks) console.log(`  - ${line}`);
  }

  if (process.argv.includes('--print-only')) {
    console.log('');
    console.log('--- what the model would be shown ---');
    console.log(text);
    return;
  }

  // `--model` overrides for one run, which is how two models are compared on one
  // week. The transport reads the environment, so setting it here is the whole
  // switch.
  const model = arg('model');
  if (model) process.env.OPENAI_MODEL = model;
  if (arg('effort')) process.env.OPENAI_REASONING_EFFORT = arg('effort')!;

  const transport = getLlmTransport();

  console.log('');
  console.log(`Asking ${transport.model}…`);

  const startedAt = Date.now();
  const result = await transport.complete(reviewPayloadFor(text, checks));
  const durationMs = Date.now() - startedAt;

  const parsed = JSON.parse(result.content) as PlanReview;
  printReport({ ...parsed, checks: checks ?? [] }, result.model, durationMs, result.usage);

  const out = arg('out');
  if (out) {
    await Bun.write(out, JSON.stringify({ plan: label, model: result.model, review: parsed }, null, 2));
    console.log('');
    console.log(`Findings written to ${out}`);
  }
}

await main();
process.exit(0);
