import { MASCOT_STATES, type MascotState } from './states';

/**
 * Where the six drawings live, and how large each is drawn.
 *
 * One table, imported by the one component that renders a mascot. A path
 * written inline anywhere else is how a set of assets ends up half-renamed —
 * the same argument `src/lib/icons.ts` makes for the glyph registry.
 */

/**
 * The public directory the six files are served from.
 *
 * `public/` rather than an import from `src/`: these are photographic-weight
 * raster assets that never change per build, and routing them through the
 * bundler would put six of them in the client graph so that one can be shown.
 * The brand marks in `public/brand/` are placed the same way.
 */
const MASCOT_DIR = '/mascot';

/**
 * State → file. WebP, because §16 of the brief asks for it and because these
 * are flat-shaded figures on transparency, which is the case WebP compresses
 * hardest — the same drawing as PNG is several times the bytes for no visible
 * difference.
 *
 * ⚠ **The files themselves are not generated by this repository.** They are the
 * designer's exports, dropped into `public/mascot/` under exactly these names —
 * see the README beside them for the export contract (transparent background,
 * square canvas, identical framing across all six). `MascotImage` degrades to
 * nothing if one is missing rather than drawing a broken-image glyph, so a
 * half-delivered set never breaks a screen.
 */
export const MASCOT_ASSETS: Record<MascotState, string> = Object.fromEntries(
  MASCOT_STATES.map((state) => [state, `${MASCOT_DIR}/state-${state}.webp`]),
) as Record<MascotState, string>;

export function mascotAssetFor(state: MascotState): string {
  return MASCOT_ASSETS[state];
}

/**
 * The three sizes a mascot is drawn at, in px.
 *
 * Square, and the number is both the rendered box and the intrinsic size handed
 * to `next/image`. The drawings are exported on a square canvas with the figure
 * centred, so a square box crops nothing and — the point of §16 — the aspect
 * ratio cannot be stretched by a caller passing a width and forgetting a
 * height.
 *
 * Three rather than a free number: a mascot that can be any size is a mascot
 * that is a slightly different size on every screen it appears on. It is also
 * what lets `ProgressMascot` skip `sizes` on the image — a box that never
 * changes width gets the 1x/2x pair `next/image` builds for a fixed image,
 * which is the right srcset and the smallest one.
 */
export const MASCOT_SIZES = {
  /** Inline beside a line of copy — a row, a compact tile. */
  sm: 72,
  /** The default. The journey card on both the home and progress tabs. */
  md: 132,
  /** A screen that is only about the mascot. Nothing uses it yet. */
  lg: 200,
} as const;

export type MascotSize = keyof typeof MASCOT_SIZES;
